PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_10_07_183839_create_oauth_auth_codes_table',1);
INSERT INTO migrations VALUES(5,'2025_10_07_183840_create_oauth_access_tokens_table',1);
INSERT INTO migrations VALUES(6,'2025_10_07_183841_create_oauth_refresh_tokens_table',1);
INSERT INTO migrations VALUES(7,'2025_10_07_183842_create_oauth_clients_table',1);
INSERT INTO migrations VALUES(8,'2025_10_07_183843_create_oauth_device_codes_table',1);
INSERT INTO migrations VALUES(9,'2025_10_07_214857_create_stores_table',1);
INSERT INTO migrations VALUES(10,'2025_10_07_215451_create_customers_table',1);
INSERT INTO migrations VALUES(11,'2025_10_07_220131_create_staff_table',1);
INSERT INTO migrations VALUES(12,'2025_10_07_221417_create_language_table',1);
INSERT INTO migrations VALUES(13,'2025_10_07_222335_create_category_table',1);
INSERT INTO migrations VALUES(14,'2025_10_07_223256_create_film_table',1);
INSERT INTO migrations VALUES(15,'2025_10_07_224533_create_inventory_table',1);
INSERT INTO migrations VALUES(16,'2025_10_08_132237_create_actors_table',1);
INSERT INTO migrations VALUES(17,'2025_10_08_132338_create_directors_table',1);
INSERT INTO migrations VALUES(18,'2025_10_08_132450_create_film_actors_table',1);
INSERT INTO migrations VALUES(19,'2025_10_08_132501_create_film_directors_table',1);
INSERT INTO migrations VALUES(20,'2025_10_08_132557_add_omdb_fields_to_film_table',1);
INSERT INTO migrations VALUES(21,'2025_10_10_182041_add_category_id_to_film_table',1);
INSERT INTO migrations VALUES(22,'2025_10_12_000000_create_addresses_table',1);
INSERT INTO migrations VALUES(23,'2025_10_12_100000_add_role_to_users',1);
INSERT INTO migrations VALUES(24,'2025_10_13_044349_create_rentals_table',1);
INSERT INTO migrations VALUES(25,'2025_10_13_045210_add_late_fees_to_rentals_table',1);
INSERT INTO migrations VALUES(26,'2025_10_13_192955_modify_users_table_add_role_enum',1);
INSERT INTO migrations VALUES(27,'2025_10_13_214856_create_countries_table',1);
INSERT INTO migrations VALUES(28,'2025_10_13_214857_create_cities_table',1);
INSERT INTO migrations VALUES(29,'2025_10_13_235312_add_staff_and_store_to_users_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "username" varchar, "role" varchar check ("role" in ('admin', 'employee', 'customer')) not null default 'customer', "staff_id" integer, "store_id" integer, "last_login_at" datetime);
INSERT INTO users VALUES(1,'Juan Pérez','juan.perez@sakila.com',NULL,'$2y$12$nTLPwfbQGSuVc9djhQi7husGvIa5OwMFfHyQsm23r399a/yzr8KKy',NULL,'2025-10-15 15:35:31','2025-10-15 16:29:03',NULL,'employee',NULL,NULL,'2025-10-15 16:29:03');
INSERT INTO users VALUES(2,'María García','maria.garcia@sakila.com',NULL,'$2y$12$0bX39U8JB0vQ6NVg9s7vSuTMKD8h6EZ3DSo./JVmRWNLpoYE6TI72',NULL,'2025-10-15 15:35:32','2025-10-15 15:35:32',NULL,'employee',NULL,NULL,NULL);
INSERT INTO users VALUES(3,'Admin Sistema','admin@sakila.com',NULL,'$2y$12$z2SkDJlL3GU/u7cSWTRS6OloiEpKPv/ort47WkhMKmdrw7u3bZCgK',NULL,'2025-10-15 15:35:32','2025-10-15 15:41:20',NULL,'admin',NULL,NULL,'2025-10-15 15:41:20');
INSERT INTO users VALUES(4,'Test User','test@example.com','2025-10-15 15:35:33','$2y$12$G9CGA5fGX0NWWKHZJSX1c.EA.6u69zDR34XVEk5XWP3bVHnn786lu','1Pa9CRKeuw','2025-10-15 15:35:34','2025-10-15 15:35:34',NULL,'customer',NULL,NULL,NULL);
INSERT INTO users VALUES(5,'david','hola@gmail.com',NULL,'$2y$12$YGgRa8.OHzaXu3mmgoLSLu4w/LOUvmK1lJQHpJ56FJToQ0YEidV/e',NULL,'2025-10-15 16:29:27','2025-10-15 16:30:13',NULL,'customer',NULL,NULL,'2025-10-15 16:30:13');
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('Np9RT8DULbSxMdpifCZlFV6XyeLzEkx5S4LXrW5p',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0','YTozOntzOjY6Il90b2tlbiI7czo0MDoidGlQVmN2a1Bkb2dVWURSNHBuWjRReHFyZXA4OEJUbERuelRZbHNtWCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjU6Imh0dHA6Ly9sYXJhdmVsLnRlc3QvbG9naW4iO319',1760545813);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "oauth_auth_codes" ("id" varchar not null, "user_id" integer not null, "client_id" varchar not null, "scopes" text, "revoked" tinyint(1) not null, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" ("id" varchar not null, "user_id" integer, "client_id" varchar not null, "name" varchar, "scopes" text, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_refresh_tokens" ("id" varchar not null, "access_token_id" varchar not null, "revoked" tinyint(1) not null, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_clients" ("id" varchar not null, "owner_type" varchar, "owner_id" integer, "name" varchar not null, "secret" varchar, "provider" varchar, "redirect_uris" text not null, "grant_types" text not null, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_device_codes" ("id" varchar not null, "user_id" integer, "client_id" varchar not null, "user_code" varchar not null, "scopes" text not null, "revoked" tinyint(1) not null, "user_approved_at" datetime, "last_polled_at" datetime, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "stores" ("store_id" integer primary key autoincrement not null, "manager_staff_id" integer not null, "address_id" integer not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO stores VALUES(1,2,2,'2025-10-15 15:35:33');
INSERT INTO stores VALUES(2,1,3,'2025-10-15 15:35:33');
INSERT INTO stores VALUES(3,3,4,'2025-10-15 15:35:33');
CREATE TABLE IF NOT EXISTS "customers" ("customer_id" integer primary key autoincrement not null, "store_id" integer not null, "first_name" varchar not null, "last_name" varchar not null, "email" varchar, "address_id" integer not null, "active" tinyint(1) not null default '1', "create_date" datetime not null default CURRENT_TIMESTAMP, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO customers VALUES(1,1,'david',' ','hola@gmail.com',5,1,'2025-10-15 16:29:27','2025-10-15 16:29:27');
CREATE TABLE IF NOT EXISTS "staff" ("staff_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "address_id" integer not null, "picture" blob, "email" varchar, "store_id" integer, "active" tinyint(1) not null default '1', "username" varchar not null, "password" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO staff VALUES(1,'Juan','Pérez',1,NULL,'juan.perez@sakila.com',2,1,'juanperez','$2y$12$StaSdXUweUQgsKtcIRkhVOHsWyHXI1UGUYAqCzEN.03QOZppYkL0e','2025-10-15 15:35:31');
INSERT INTO staff VALUES(2,'María','García',1,NULL,'maria.garcia@sakila.com',1,1,'mariagarcia','$2y$12$StQeIDq2OxKHxJuaR9pZae/c8ylk8Umzay4n3VTZHSV.CYW7wVTp.','2025-10-15 15:35:32');
INSERT INTO staff VALUES(3,'Admin','Sistema',1,NULL,'admin@sakila.com',3,1,'admin','$2y$12$K3IrZLRBATc8ZJvetiJ4YecpA/6JYG7ue7dtCHFZtX3qWv7bB.JIq','2025-10-15 15:35:33');
CREATE TABLE IF NOT EXISTS "language" ("language_id" integer primary key autoincrement not null, "name" varchar not null, "code" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO language VALUES(1,'Inglés','en','2025-10-15 15:35:33');
INSERT INTO language VALUES(2,'Español','es','2025-10-15 15:35:33');
CREATE TABLE IF NOT EXISTS "category" ("category_id" integer primary key autoincrement not null, "name" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO category VALUES(1,'Acción','2025-10-15 15:35:33');
INSERT INTO category VALUES(2,'Aventura','2025-10-15 15:35:33');
INSERT INTO category VALUES(3,'Comedia','2025-10-15 15:35:33');
INSERT INTO category VALUES(4,'Drama','2025-10-15 15:35:33');
INSERT INTO category VALUES(5,'Ciencia Ficción','2025-10-15 15:35:33');
INSERT INTO category VALUES(6,'Terror','2025-10-15 15:35:33');
INSERT INTO category VALUES(7,'Romance','2025-10-15 15:35:33');
INSERT INTO category VALUES(8,'Animación','2025-10-15 15:35:33');
INSERT INTO category VALUES(9,'Documental','2025-10-15 15:35:33');
INSERT INTO category VALUES(10,'Thriller','2025-10-15 15:35:33');
INSERT INTO category VALUES(11,'Misterio','2025-10-15 15:35:33');
INSERT INTO category VALUES(12,'Musical','2025-10-15 15:35:33');
INSERT INTO category VALUES(13,'Fantasía','2025-10-15 15:35:33');
INSERT INTO category VALUES(14,'Western','2025-10-15 15:35:33');
INSERT INTO category VALUES(15,'Deportes','2025-10-15 15:35:33');
INSERT INTO category VALUES(16,'Familiar','2025-10-15 15:35:33');
CREATE TABLE IF NOT EXISTS "inventory" ("inventory_id" integer primary key autoincrement not null, "film_id" integer not null, "store_id" integer not null, "last_update" datetime not null default CURRENT_TIMESTAMP, foreign key("film_id") references "film"("film_id") on delete restrict on update cascade, foreign key("store_id") references "stores"("store_id") on delete restrict on update cascade);
CREATE TABLE IF NOT EXISTS "actors" ("actor_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "biography" text, "birth_date" date, "birth_place" varchar, "imdb_id" varchar, "photo_url" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "directors" ("director_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "biography" text, "birth_date" date, "birth_place" varchar, "imdb_id" varchar, "photo_url" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "film_actors" ("id" integer primary key autoincrement not null, "film_id" integer not null, "actor_id" integer not null, "character_name" varchar, "order" integer, "created_at" datetime, "updated_at" datetime, foreign key("film_id") references "film"("film_id") on delete cascade, foreign key("actor_id") references "actors"("actor_id") on delete cascade);
CREATE TABLE IF NOT EXISTS "film_directors" ("id" integer primary key autoincrement not null, "film_id" integer not null, "director_id" integer not null, "role" varchar not null default 'Director', "created_at" datetime, "updated_at" datetime, foreign key("film_id") references "film"("film_id") on delete cascade, foreign key("director_id") references "directors"("director_id") on delete cascade);
CREATE TABLE IF NOT EXISTS "film" ("film_id" integer primary key autoincrement not null, "title" varchar not null, "description" text, "release_year" integer, "language_id" integer not null, "original_language_id" integer, "rental_duration" integer not null default ('3'), "rental_rate" numeric not null default ('4.99'), "length" integer, "replacement_cost" numeric not null default ('19.99'), "rating" varchar not null default ('G'), "special_features" text, "last_update" datetime not null default (CURRENT_TIMESTAMP), "imdb_id" varchar, "poster_url" varchar, "imdb_rating" numeric, "imdb_votes" integer, "metascore" integer, "plot" text, "awards" varchar, "box_office" varchar, "production" varchar, "website" varchar, "writers" text, "countries" text, "imported_from_omdb" tinyint(1) not null default ('0'), "category_id" integer, foreign key("original_language_id") references language("language_id") on delete set null on update no action, foreign key("language_id") references language("language_id") on delete restrict on update no action, foreign key("category_id") references "category"("category_id") on delete set null);
CREATE TABLE IF NOT EXISTS "addresses" ("address_id" integer primary key autoincrement not null, "address" varchar not null, "address2" varchar, "district" varchar, "city_id" integer, "postal_code" varchar, "phone" varchar, "last_update" datetime not null default CURRENT_TIMESTAMP, foreign key("city_id") references "cities"("city_id") on delete restrict on update cascade);
INSERT INTO addresses VALUES(1,'Calle Principal 123',NULL,'Centro',1,'12345','555-0123','2025-10-15 15:35:33');
INSERT INTO addresses VALUES(2,'Av. Insurgentes Sur 1234',NULL,'Coyoacán',1,'04510','5555123456','2025-10-15 15:35:33');
INSERT INTO addresses VALUES(3,'Av. Vallarta 3000',NULL,'Zapopan',2,'45040','3336789012','2025-10-15 15:35:33');
INSERT INTO addresses VALUES(4,'Av. Gonzalitos 500',NULL,'San Nicolás',3,'66450','8181234567','2025-10-15 15:35:33');
INSERT INTO addresses VALUES(5,'gotica',NULL,NULL,NULL,'22222','1234','2025-10-15 16:29:27');
CREATE TABLE IF NOT EXISTS "rentals" ("rental_id" integer primary key autoincrement not null, "inventory_id" integer not null, "customer_id" integer not null, "staff_id" integer not null, "rental_date" datetime not null, "return_date" datetime, "rental_amount" numeric not null, "status" varchar check ("status" in ('active', 'returned', 'overdue')) not null default 'active', "notes" text, "last_update" datetime not null default CURRENT_TIMESTAMP, "late_fee" numeric not null default '0', "due_date" datetime, "late_fee_applied" tinyint(1) not null default '0', foreign key("inventory_id") references "inventory"("inventory_id"), foreign key("customer_id") references "customers"("customer_id"), foreign key("staff_id") references "staff"("staff_id"));
CREATE TABLE IF NOT EXISTS "countries" ("country_id" integer primary key autoincrement not null, "country" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO countries VALUES(1,'México','2025-10-15 15:35:32');
INSERT INTO countries VALUES(2,'Estados Unidos','2025-10-15 15:35:32');
INSERT INTO countries VALUES(3,'Canadá','2025-10-15 15:35:32');
INSERT INTO countries VALUES(4,'España','2025-10-15 15:35:32');
INSERT INTO countries VALUES(5,'Argentina','2025-10-15 15:35:32');
CREATE TABLE IF NOT EXISTS "cities" ("city_id" integer primary key autoincrement not null, "city" varchar not null, "country_id" integer not null, "last_update" datetime not null default CURRENT_TIMESTAMP, foreign key("country_id") references "countries"("country_id") on delete restrict on update cascade);
INSERT INTO cities VALUES(1,'Ciudad de México',1,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(2,'Guadalajara',1,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(3,'Monterrey',1,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(4,'New York',2,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(5,'Los Angeles',2,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(6,'Chicago',2,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(7,'Toronto',3,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(8,'Vancouver',3,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(9,'Montreal',3,'2025-10-15 15:35:32');
INSERT INTO cities VALUES(10,'Madrid',4,'2025-10-15 15:35:33');
INSERT INTO cities VALUES(11,'Barcelona',4,'2025-10-15 15:35:33');
INSERT INTO cities VALUES(12,'Valencia',4,'2025-10-15 15:35:33');
INSERT INTO cities VALUES(13,'Buenos Aires',5,'2025-10-15 15:35:33');
INSERT INTO cities VALUES(14,'Córdoba',5,'2025-10-15 15:35:33');
INSERT INTO cities VALUES(15,'Rosario',5,'2025-10-15 15:35:33');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',29);
INSERT INTO sqlite_sequence VALUES('film',0);
INSERT INTO sqlite_sequence VALUES('countries',5);
INSERT INTO sqlite_sequence VALUES('cities',15);
INSERT INTO sqlite_sequence VALUES('category',16);
INSERT INTO sqlite_sequence VALUES('language',2);
INSERT INTO sqlite_sequence VALUES('addresses',5);
INSERT INTO sqlite_sequence VALUES('users',5);
INSERT INTO sqlite_sequence VALUES('staff',3);
INSERT INTO sqlite_sequence VALUES('stores',3);
INSERT INTO sqlite_sequence VALUES('customers',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "oauth_auth_codes_user_id_index" on "oauth_auth_codes" ("user_id");
CREATE INDEX "oauth_access_tokens_user_id_index" on "oauth_access_tokens" ("user_id");
CREATE INDEX "oauth_refresh_tokens_access_token_id_index" on "oauth_refresh_tokens" ("access_token_id");
CREATE INDEX "oauth_clients_owner_type_owner_id_index" on "oauth_clients" ("owner_type", "owner_id");
CREATE INDEX "oauth_device_codes_user_id_index" on "oauth_device_codes" ("user_id");
CREATE INDEX "oauth_device_codes_client_id_index" on "oauth_device_codes" ("client_id");
CREATE UNIQUE INDEX "oauth_device_codes_user_code_unique" on "oauth_device_codes" ("user_code");
CREATE INDEX "customers_store_id_index" on "customers" ("store_id");
CREATE INDEX "customers_address_id_index" on "customers" ("address_id");
CREATE INDEX "customers_active_index" on "customers" ("active");
CREATE INDEX "customers_last_name_first_name_index" on "customers" ("last_name", "first_name");
CREATE INDEX "staff_store_id_index" on "staff" ("store_id");
CREATE INDEX "staff_address_id_index" on "staff" ("address_id");
CREATE INDEX "staff_active_index" on "staff" ("active");
CREATE INDEX "staff_last_name_first_name_index" on "staff" ("last_name", "first_name");
CREATE INDEX "staff_email_index" on "staff" ("email");
CREATE UNIQUE INDEX "staff_username_unique" on "staff" ("username");
CREATE INDEX "language_name_index" on "language" ("name");
CREATE UNIQUE INDEX "language_name_unique" on "language" ("name");
CREATE UNIQUE INDEX "language_code_unique" on "language" ("code");
CREATE INDEX "idx_category_name" on "category" ("name");
CREATE UNIQUE INDEX "category_name_unique" on "category" ("name");
CREATE INDEX "inventory_film_id_index" on "inventory" ("film_id");
CREATE INDEX "inventory_store_id_index" on "inventory" ("store_id");
CREATE INDEX "inventory_film_id_store_id_index" on "inventory" ("film_id", "store_id");
CREATE INDEX "inventory_last_update_index" on "inventory" ("last_update");
CREATE INDEX "actors_first_name_last_name_index" on "actors" ("first_name", "last_name");
CREATE INDEX "actors_imdb_id_index" on "actors" ("imdb_id");
CREATE UNIQUE INDEX "actors_imdb_id_unique" on "actors" ("imdb_id");
CREATE INDEX "directors_first_name_last_name_index" on "directors" ("first_name", "last_name");
CREATE INDEX "directors_imdb_id_index" on "directors" ("imdb_id");
CREATE UNIQUE INDEX "directors_imdb_id_unique" on "directors" ("imdb_id");
CREATE UNIQUE INDEX "film_actors_film_id_actor_id_unique" on "film_actors" ("film_id", "actor_id");
CREATE INDEX "film_actors_film_id_index" on "film_actors" ("film_id");
CREATE INDEX "film_actors_actor_id_index" on "film_actors" ("actor_id");
CREATE UNIQUE INDEX "film_directors_film_id_director_id_unique" on "film_directors" ("film_id", "director_id");
CREATE INDEX "film_directors_film_id_index" on "film_directors" ("film_id");
CREATE INDEX "film_directors_director_id_index" on "film_directors" ("director_id");
CREATE INDEX "film_imdb_id_index" on "film" ("imdb_id");
CREATE UNIQUE INDEX "film_imdb_id_unique" on "film" ("imdb_id");
CREATE INDEX "film_imdb_rating_index" on "film" ("imdb_rating");
CREATE INDEX "film_imported_from_omdb_index" on "film" ("imported_from_omdb");
CREATE INDEX "idx_film_language_id" on "film" ("language_id");
CREATE INDEX "idx_film_length" on "film" ("length");
CREATE INDEX "idx_film_original_language_id" on "film" ("original_language_id");
CREATE INDEX "idx_film_rating" on "film" ("rating");
CREATE INDEX "idx_film_release_year" on "film" ("release_year");
CREATE INDEX "idx_film_rental_rate" on "film" ("rental_rate");
CREATE INDEX "idx_film_title" on "film" ("title");
CREATE INDEX "film_category_id_index" on "film" ("category_id");
CREATE INDEX "addresses_postal_code_index" on "addresses" ("postal_code");
CREATE INDEX "rentals_rental_date_index" on "rentals" ("rental_date");
CREATE INDEX "rentals_return_date_index" on "rentals" ("return_date");
CREATE INDEX "rentals_status_index" on "rentals" ("status");
CREATE INDEX "rentals_customer_id_rental_date_index" on "rentals" ("customer_id", "rental_date");
CREATE INDEX "rentals_inventory_id_rental_date_index" on "rentals" ("inventory_id", "rental_date");
CREATE INDEX "users_staff_id_index" on "users" ("staff_id");
CREATE INDEX "users_store_id_index" on "users" ("store_id");
COMMIT;
