PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_10_07_183839_create_oauth_auth_codes_table',1);
INSERT INTO migrations VALUES(5,'2025_10_07_183840_create_oauth_access_tokens_table',1);
INSERT INTO migrations VALUES(6,'2025_10_07_183841_create_oauth_refresh_tokens_table',1);
INSERT INTO migrations VALUES(7,'2025_10_07_183842_create_oauth_clients_table',1);
INSERT INTO migrations VALUES(8,'2025_10_07_183843_create_oauth_device_codes_table',1);
INSERT INTO migrations VALUES(9,'2025_10_07_214857_create_stores_table',1);
INSERT INTO migrations VALUES(10,'2025_10_07_215451_create_customers_table',1);
INSERT INTO migrations VALUES(11,'2025_10_07_220131_create_staff_table',1);
INSERT INTO migrations VALUES(12,'2025_10_07_221417_create_language_table',1);
INSERT INTO migrations VALUES(13,'2025_10_07_222335_create_category_table',1);
INSERT INTO migrations VALUES(14,'2025_10_07_223256_create_film_table',1);
INSERT INTO migrations VALUES(15,'2025_10_07_224533_create_inventory_table',1);
INSERT INTO migrations VALUES(16,'2025_10_08_132237_create_actors_table',1);
INSERT INTO migrations VALUES(17,'2025_10_08_132338_create_directors_table',1);
INSERT INTO migrations VALUES(18,'2025_10_08_132450_create_film_actors_table',1);
INSERT INTO migrations VALUES(19,'2025_10_08_132501_create_film_directors_table',1);
INSERT INTO migrations VALUES(20,'2025_10_08_132557_add_omdb_fields_to_film_table',1);
INSERT INTO migrations VALUES(21,'2025_10_10_182041_add_category_id_to_film_table',1);
INSERT INTO migrations VALUES(22,'2025_10_12_000000_create_addresses_table',1);
INSERT INTO migrations VALUES(23,'2025_10_12_100000_add_role_to_users',1);
INSERT INTO migrations VALUES(24,'2025_10_13_044349_create_rentals_table',1);
INSERT INTO migrations VALUES(25,'2025_10_13_045210_add_late_fees_to_rentals_table',1);
INSERT INTO migrations VALUES(26,'2025_10_13_192955_modify_users_table_add_role_enum',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "username" varchar, "role" varchar check ("role" in ('admin', 'employee', 'customer')) not null default 'customer');
INSERT INTO users VALUES(1,'Juan Pérez','juan.perez@sakila.com',NULL,'$2y$12$fmFmjTHhYsg0BRasZ/nvXOcI13htiCy8ZAJa3pScKEVaHQ2hZGeP6',NULL,'2025-10-13 19:35:24','2025-10-13 19:35:24',NULL,'employee');
INSERT INTO users VALUES(2,'María García','maria.garcia@sakila.com',NULL,'$2y$12$pAbr3E04DBg7lJUozhTLoebbdUmR2oWntDWi5n1691jwmko3wHvyK',NULL,'2025-10-13 19:35:25','2025-10-13 19:35:25',NULL,'employee');
INSERT INTO users VALUES(3,'Admin Sistema','admin@sakila.com',NULL,'$2y$12$QxQBd8Nd5Nt1HLINnRTD.OqvJkCYRTYgKVZXAA0qylLsW.yvsIsae',NULL,'2025-10-13 19:35:27','2025-10-13 19:35:27',NULL,'admin');
INSERT INTO users VALUES(4,'Test User','test@example.com','2025-10-13 19:35:28','$2y$12$FMVB7MJ6thcILRgGuhFvT.nj4P1zj5NiUEsZvrIPZE5JxGOVHjP7C','q4U3dN1Bzz','2025-10-13 19:35:28','2025-10-13 19:35:28',NULL,'customer');
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('hRfFImsRp6Hr95zH3RZNkKQoReiWcjQy4Ys445kT',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiVUJ3TUQ1NnBWaVphZ1czc3pzaExXUGZVVmlDR3RqMGkxYlV2SjdLcCI7czozOiJ1cmwiO2E6MTp7czo4OiJpbnRlbmRlZCI7czozNjoiaHR0cDovL2xhcmF2ZWwudGVzdC9jdXN0b21lcnMvY3JlYXRlIjt9czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MzY6Imh0dHA6Ly9sYXJhdmVsLnRlc3QvY3VzdG9tZXJzL2NyZWF0ZSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=',1760384688);
INSERT INTO sessions VALUES('saLLABAcnZZoafTGJLTPPIj0BU6BacNrQNKu9wNH',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0','YTozOntzOjY6Il90b2tlbiI7czo0MDoicEhrSVJvbTh5ZGtJOW80dEdMYzhYc0FvSVBqSmRHWXI2MURBVm1zeiI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjU6Imh0dHA6Ly9sYXJhdmVsLnRlc3QvbG9naW4iO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX19',1760384688);
INSERT INTO sessions VALUES('Ih2CcYetyh4ZhMFwsXLbzHBlYrEFffTbtaFuvoGZ',3,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiTThLcHJFU1puYVd4c3FickdDdDBFNTZLcmh5MG1SRUhoWTd3SjRYUiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjU6Imh0dHA6Ly9sYXJhdmVsLnRlc3Qvc3RhZmYiO31zOjUwOiJsb2dpbl93ZWJfNTliYTM2YWRkYzJiMmY5NDAxNTgwZjAxNGM3ZjU4ZWE0ZTMwOTg5ZCI7aTozO30=',1760384879);
INSERT INTO sessions VALUES('3yZ9j4MWUXNSgQ7qBW8bXhhhcsOe3iMUdilDMLYn',1,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiT25VM3ZQQ3RnRWw1ZVdNeTZHSFczMUk2QmVJczdwYjlPQW43amJlTCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjY6Imh0dHA6Ly9sYXJhdmVsLnRlc3Qvc3RvcmVzIjt9czo1MDoibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO2k6MTt9',1760395322);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "oauth_auth_codes" ("id" varchar not null, "user_id" integer not null, "client_id" varchar not null, "scopes" text, "revoked" tinyint(1) not null, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" ("id" varchar not null, "user_id" integer, "client_id" varchar not null, "name" varchar, "scopes" text, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_refresh_tokens" ("id" varchar not null, "access_token_id" varchar not null, "revoked" tinyint(1) not null, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_clients" ("id" varchar not null, "owner_type" varchar, "owner_id" integer, "name" varchar not null, "secret" varchar, "provider" varchar, "redirect_uris" text not null, "grant_types" text not null, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "oauth_device_codes" ("id" varchar not null, "user_id" integer, "client_id" varchar not null, "user_code" varchar not null, "scopes" text not null, "revoked" tinyint(1) not null, "user_approved_at" datetime, "last_polled_at" datetime, "expires_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "stores" ("store_id" integer primary key autoincrement not null, "manager_staff_id" integer not null, "address_id" integer not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO stores VALUES(1,1,1,'2025-10-13 19:35:24');
INSERT INTO stores VALUES(2,1,1,'2025-10-13 22:38:27');
CREATE TABLE IF NOT EXISTS "customers" ("customer_id" integer primary key autoincrement not null, "store_id" integer not null, "first_name" varchar not null, "last_name" varchar not null, "email" varchar, "address_id" integer not null, "active" tinyint(1) not null default '1', "create_date" datetime not null default CURRENT_TIMESTAMP, "last_update" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "staff" ("staff_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "address_id" integer not null, "picture" blob, "email" varchar, "store_id" integer not null, "active" tinyint(1) not null default '1', "username" varchar not null, "password" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO staff VALUES(1,'Juan','Pérez',1,NULL,'juan.perez@sakila.com',2,1,'juanperez','$2y$12$QzzpUetLbPzIwEsptvn61uYwtZ9seFUK00Tl0APzfmmvTGJ..eytS','2025-10-13 19:35:25');
INSERT INTO staff VALUES(2,'María','García',1,NULL,'maria.garcia@sakila.com',1,1,'mariagarcia','$2y$12$1gbtIuYBPVvWYzzeY62S3emu6CiPN/uZ.2CDjXEzivnZVSF2XDUki','2025-10-13 19:35:26');
INSERT INTO staff VALUES(3,'Admin','Sistema',1,NULL,'admin@sakila.com',1,1,'admin','$2y$12$Jl0.Bx3DzPUlEKSr8idO9.Fsm42FVzGPp4AO7ud5bXUS/uzK7fZyG','2025-10-13 19:35:28');
CREATE TABLE IF NOT EXISTS "language" ("language_id" integer primary key autoincrement not null, "name" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO language VALUES(1,'English','2025-10-13 22:40:49');
CREATE TABLE IF NOT EXISTS "category" ("category_id" integer primary key autoincrement not null, "name" varchar not null, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO category VALUES(1,'Crime','2025-10-13 22:40:49');
INSERT INTO category VALUES(2,'Action','2025-10-13 22:41:02');
INSERT INTO category VALUES(3,'Biography','2025-10-13 22:41:18');
CREATE TABLE IF NOT EXISTS "inventory" ("inventory_id" integer primary key autoincrement not null, "film_id" integer not null, "store_id" integer not null, "last_update" datetime not null default CURRENT_TIMESTAMP, foreign key("film_id") references "film"("film_id") on delete restrict on update cascade, foreign key("store_id") references "stores"("store_id") on delete restrict on update cascade);
CREATE TABLE IF NOT EXISTS "actors" ("actor_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "biography" text, "birth_date" date, "birth_place" varchar, "imdb_id" varchar, "photo_url" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO actors VALUES(1,'Marlon','Brando',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO actors VALUES(2,'Al','Pacino',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO actors VALUES(3,'James','Caan',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO actors VALUES(4,'Jeff','Bridges',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO actors VALUES(5,'Garrett','Hedlund',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO actors VALUES(6,'Olivia','Wilde',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO actors VALUES(7,'Robert','De Niro',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:18','2025-10-13 22:41:18');
INSERT INTO actors VALUES(8,'Ray','Liotta',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:18','2025-10-13 22:41:18');
INSERT INTO actors VALUES(9,'Joe','Pesci',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:18','2025-10-13 22:41:18');
CREATE TABLE IF NOT EXISTS "directors" ("director_id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "biography" text, "birth_date" date, "birth_place" varchar, "imdb_id" varchar, "photo_url" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO directors VALUES(1,'Francis','Ford Coppola',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO directors VALUES(2,'Joseph','Kosinski',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO directors VALUES(3,'Martin','Scorsese',NULL,NULL,NULL,NULL,NULL,'2025-10-13 22:41:18','2025-10-13 22:41:18');
CREATE TABLE IF NOT EXISTS "film_actors" ("id" integer primary key autoincrement not null, "film_id" integer not null, "actor_id" integer not null, "character_name" varchar, "order" integer, "created_at" datetime, "updated_at" datetime, foreign key("film_id") references "film"("film_id") on delete cascade, foreign key("actor_id") references "actors"("actor_id") on delete cascade);
INSERT INTO film_actors VALUES(1,1,1,NULL,1,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO film_actors VALUES(2,1,2,NULL,2,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO film_actors VALUES(3,1,3,NULL,3,'2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO film_actors VALUES(4,2,4,NULL,1,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO film_actors VALUES(5,2,5,NULL,2,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO film_actors VALUES(6,2,6,NULL,3,'2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO film_actors VALUES(7,3,7,NULL,1,'2025-10-13 22:41:18','2025-10-13 22:41:18');
INSERT INTO film_actors VALUES(8,3,8,NULL,2,'2025-10-13 22:41:18','2025-10-13 22:41:18');
INSERT INTO film_actors VALUES(9,3,9,NULL,3,'2025-10-13 22:41:18','2025-10-13 22:41:18');
CREATE TABLE IF NOT EXISTS "film_directors" ("id" integer primary key autoincrement not null, "film_id" integer not null, "director_id" integer not null, "role" varchar not null default 'Director', "created_at" datetime, "updated_at" datetime, foreign key("film_id") references "film"("film_id") on delete cascade, foreign key("director_id") references "directors"("director_id") on delete cascade);
INSERT INTO film_directors VALUES(1,1,1,'Director','2025-10-13 22:40:49','2025-10-13 22:40:49');
INSERT INTO film_directors VALUES(2,2,2,'Director','2025-10-13 22:41:02','2025-10-13 22:41:02');
INSERT INTO film_directors VALUES(3,3,3,'Director','2025-10-13 22:41:18','2025-10-13 22:41:18');
CREATE TABLE IF NOT EXISTS "film" ("film_id" integer primary key autoincrement not null, "title" varchar not null, "description" text, "release_year" integer, "language_id" integer not null, "original_language_id" integer, "rental_duration" integer not null default ('3'), "rental_rate" numeric not null default ('4.99'), "length" integer, "replacement_cost" numeric not null default ('19.99'), "rating" varchar not null default ('G'), "special_features" text, "last_update" datetime not null default (CURRENT_TIMESTAMP), "imdb_id" varchar, "poster_url" varchar, "imdb_rating" numeric, "imdb_votes" integer, "metascore" integer, "plot" text, "awards" varchar, "box_office" varchar, "production" varchar, "website" varchar, "writers" text, "countries" text, "imported_from_omdb" tinyint(1) not null default ('0'), "category_id" integer, foreign key("original_language_id") references language("language_id") on delete set null on update no action, foreign key("language_id") references language("language_id") on delete restrict on update no action, foreign key("category_id") references "category"("category_id") on delete set null);
INSERT INTO film VALUES(1,'The Godfather','The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter''s wedding. Michael, Vito''s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don''s influence for the same, Vito refuses to do it. What follows is a clash between Vito''s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.',1972,1,1,3,4.99000000000000021,175,19.9899999999999984,'R',NULL,'2025-10-13 22:40:49','tt0068646','https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg',9.19999999999999928,2160424,100,'The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter''s wedding. Michael, Vito''s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don''s influence for the same, Vito refuses to do it. What follows is a clash between Vito''s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.','Won 3 Oscars. 31 wins & 31 nominations total','$136,381,073','N/A',NULL,'["Mario Puzo","Francis Ford Coppola"]','["United States"]',1,1);
INSERT INTO film VALUES(2,'Tron: Legacy','Sam Flynn, the tech-savvy 27-year-old son of Kevin Flynn, looks into his father''s disappearance and finds himself pulled into the same world of fierce programs and gladiatorial games where his father has been living for 20 years. Along with Kevin''s loyal confidant Quorra, father and son embark on a life-and-death journey across a visually-stunning cyber universe that has become far more advanced and exceedingly dangerous. Meanwhile, the malevolent program CLU, who dominates the digital world, plans to invade the real world and will stop at nothing to prevent their escape.',2010,1,1,3,4.99000000000000021,125,19.9899999999999984,'PG',NULL,'2025-10-13 22:41:02','tt1104001','https://m.media-amazon.com/images/M/MV5BMTk4NTk4MTk1OF5BMl5BanBnXkFtZTcwNTE2MDIwNA@@._V1_SX300.jpg',6.79999999999999982,372296,49,'Sam Flynn, the tech-savvy 27-year-old son of Kevin Flynn, looks into his father''s disappearance and finds himself pulled into the same world of fierce programs and gladiatorial games where his father has been living for 20 years. Along with Kevin''s loyal confidant Quorra, father and son embark on a life-and-death journey across a visually-stunning cyber universe that has become far more advanced and exceedingly dangerous. Meanwhile, the malevolent program CLU, who dominates the digital world, plans to invade the real world and will stop at nothing to prevent their escape.','Nominated for 1 Oscar. 10 wins & 52 nominations total','$172,062,763','N/A',NULL,'["Edward Kitsis","Adam Horowitz","Brian Klugman"]','["United States","India","United Kingdom","Mexico","Japan","Canada"]',1,2);
INSERT INTO film VALUES(3,'Goodfellas','Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners'' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?',1990,1,1,3,4.99000000000000021,145,19.9899999999999984,'R',NULL,'2025-10-13 22:41:18','tt0099685','https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg',8.69999999999999929,1350647,92,'Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners'' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?','Won 1 Oscar. 44 wins & 38 nominations total','$46,909,721','N/A',NULL,'["Nicholas Pileggi","Martin Scorsese"]','["United States"]',1,3);
CREATE TABLE IF NOT EXISTS "addresses" ("address_id" integer primary key autoincrement not null, "address" varchar not null, "address2" varchar, "district" varchar, "city" varchar, "postal_code" varchar, "phone" varchar, "last_update" datetime not null default CURRENT_TIMESTAMP);
INSERT INTO addresses VALUES(1,'Calle Principal 123',NULL,'Centro','Ciudad Ejemplo','12345','555-0123','2025-10-13 19:35:24');
CREATE TABLE IF NOT EXISTS "rentals" ("rental_id" integer primary key autoincrement not null, "inventory_id" integer not null, "customer_id" integer not null, "staff_id" integer not null, "rental_date" datetime not null, "return_date" datetime, "rental_amount" numeric not null, "status" varchar check ("status" in ('active', 'returned', 'overdue')) not null default 'active', "notes" text, "last_update" datetime not null default CURRENT_TIMESTAMP, "late_fee" numeric not null default '0', "due_date" datetime, "late_fee_applied" tinyint(1) not null default '0', foreign key("inventory_id") references "inventory"("inventory_id"), foreign key("customer_id") references "customers"("customer_id"), foreign key("staff_id") references "staff"("staff_id"));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',26);
INSERT INTO sqlite_sequence VALUES('film',3);
INSERT INTO sqlite_sequence VALUES('addresses',1);
INSERT INTO sqlite_sequence VALUES('stores',2);
INSERT INTO sqlite_sequence VALUES('users',4);
INSERT INTO sqlite_sequence VALUES('staff',3);
INSERT INTO sqlite_sequence VALUES('language',1);
INSERT INTO sqlite_sequence VALUES('category',3);
INSERT INTO sqlite_sequence VALUES('actors',9);
INSERT INTO sqlite_sequence VALUES('film_actors',9);
INSERT INTO sqlite_sequence VALUES('directors',3);
INSERT INTO sqlite_sequence VALUES('film_directors',3);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "oauth_auth_codes_user_id_index" on "oauth_auth_codes" ("user_id");
CREATE INDEX "oauth_access_tokens_user_id_index" on "oauth_access_tokens" ("user_id");
CREATE INDEX "oauth_refresh_tokens_access_token_id_index" on "oauth_refresh_tokens" ("access_token_id");
CREATE INDEX "oauth_clients_owner_type_owner_id_index" on "oauth_clients" ("owner_type", "owner_id");
CREATE INDEX "oauth_device_codes_user_id_index" on "oauth_device_codes" ("user_id");
CREATE INDEX "oauth_device_codes_client_id_index" on "oauth_device_codes" ("client_id");
CREATE UNIQUE INDEX "oauth_device_codes_user_code_unique" on "oauth_device_codes" ("user_code");
CREATE INDEX "customers_store_id_index" on "customers" ("store_id");
CREATE INDEX "customers_address_id_index" on "customers" ("address_id");
CREATE INDEX "customers_active_index" on "customers" ("active");
CREATE INDEX "customers_last_name_first_name_index" on "customers" ("last_name", "first_name");
CREATE INDEX "staff_store_id_index" on "staff" ("store_id");
CREATE INDEX "staff_address_id_index" on "staff" ("address_id");
CREATE INDEX "staff_active_index" on "staff" ("active");
CREATE INDEX "staff_last_name_first_name_index" on "staff" ("last_name", "first_name");
CREATE INDEX "staff_email_index" on "staff" ("email");
CREATE UNIQUE INDEX "staff_username_unique" on "staff" ("username");
CREATE INDEX "language_name_index" on "language" ("name");
CREATE UNIQUE INDEX "language_name_unique" on "language" ("name");
CREATE INDEX "idx_category_name" on "category" ("name");
CREATE UNIQUE INDEX "category_name_unique" on "category" ("name");
CREATE INDEX "inventory_film_id_index" on "inventory" ("film_id");
CREATE INDEX "inventory_store_id_index" on "inventory" ("store_id");
CREATE INDEX "inventory_film_id_store_id_index" on "inventory" ("film_id", "store_id");
CREATE INDEX "inventory_last_update_index" on "inventory" ("last_update");
CREATE INDEX "actors_first_name_last_name_index" on "actors" ("first_name", "last_name");
CREATE INDEX "actors_imdb_id_index" on "actors" ("imdb_id");
CREATE UNIQUE INDEX "actors_imdb_id_unique" on "actors" ("imdb_id");
CREATE INDEX "directors_first_name_last_name_index" on "directors" ("first_name", "last_name");
CREATE INDEX "directors_imdb_id_index" on "directors" ("imdb_id");
CREATE UNIQUE INDEX "directors_imdb_id_unique" on "directors" ("imdb_id");
CREATE UNIQUE INDEX "film_actors_film_id_actor_id_unique" on "film_actors" ("film_id", "actor_id");
CREATE INDEX "film_actors_film_id_index" on "film_actors" ("film_id");
CREATE INDEX "film_actors_actor_id_index" on "film_actors" ("actor_id");
CREATE UNIQUE INDEX "film_directors_film_id_director_id_unique" on "film_directors" ("film_id", "director_id");
CREATE INDEX "film_directors_film_id_index" on "film_directors" ("film_id");
CREATE INDEX "film_directors_director_id_index" on "film_directors" ("director_id");
CREATE INDEX "film_imdb_id_index" on "film" ("imdb_id");
CREATE UNIQUE INDEX "film_imdb_id_unique" on "film" ("imdb_id");
CREATE INDEX "film_imdb_rating_index" on "film" ("imdb_rating");
CREATE INDEX "film_imported_from_omdb_index" on "film" ("imported_from_omdb");
CREATE INDEX "idx_film_language_id" on "film" ("language_id");
CREATE INDEX "idx_film_length" on "film" ("length");
CREATE INDEX "idx_film_original_language_id" on "film" ("original_language_id");
CREATE INDEX "idx_film_rating" on "film" ("rating");
CREATE INDEX "idx_film_release_year" on "film" ("release_year");
CREATE INDEX "idx_film_rental_rate" on "film" ("rental_rate");
CREATE INDEX "idx_film_title" on "film" ("title");
CREATE INDEX "film_category_id_index" on "film" ("category_id");
CREATE INDEX "addresses_city_index" on "addresses" ("city");
CREATE INDEX "addresses_postal_code_index" on "addresses" ("postal_code");
CREATE INDEX "rentals_rental_date_index" on "rentals" ("rental_date");
CREATE INDEX "rentals_return_date_index" on "rentals" ("return_date");
CREATE INDEX "rentals_status_index" on "rentals" ("status");
CREATE INDEX "rentals_customer_id_rental_date_index" on "rentals" ("customer_id", "rental_date");
CREATE INDEX "rentals_inventory_id_rental_date_index" on "rentals" ("inventory_id", "rental_date");
COMMIT;
